# Generated by Django 5.2.4 on 2025-07-20 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(default=0)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('discount_price', models.BigIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='product')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='product')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='product')),
                ('brand', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('36-40', '36-40'), ('41-45', '41-45'), ('46-47', '46-47')], max_length=50)),
                ('product_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('review', models.TextField()),
                ('rating', models.BigIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('in_stock', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
    ]
