# Generated by Django 5.2.4 on 2025-07-20 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('subtotal', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveBigIntegerField()),
                ('subtotal', models.PositiveBigIntegerField()),
                ('order_status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('complete', 'complete'), ('cancelled', 'cancelled')], default='pending', max_length=12)),
                ('payment_method', models.CharField(choices=[('paystack', 'paystack'), ('paypal', 'paypal'), ('stripe', 'stripe'), ('transfer', 'transfer')], default='paystack', max_length=12)),
                ('ref', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.cart')),
            ],
        ),
    ]
