# Generated by Django 5.2.4 on 2025-07-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_cart_created_cartproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
